services:
  web:
    environment:
      DB_HOST: db
      DB_NAME: db
      DB_USER: db
      DB_PASS: db
      ADMIN_API_KEY: test123
      BLOG_TITLE: Dropblog Dev1
      LOCALE: de-DE
      TIMEZONE: Europe/Berlin
      DATE_FORMAT: d. F Y
      DEBUG: "true"
