name: Deploy Blog

on:
  push:
    branches: [ pain ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  
    
    - name: Set up PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer
    
    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader
    
    - name: Create config.php
      run: |
        sed -e "s/{{DB_HOST}}/${{ vars.DB_HOST }}/g" \
            -e "s/{{DB_NAME}}/${{ vars.DB_NAME }}/g" \
            -e "s/{{DB_USER}}/${{ secrets.DB_USER }}/g" \
            -e "s/{{DB_PASS}}/${{ secrets.DB_PASS }}/g" \
            -e "s/{{ADMIN_API_KEY}}/${{ secrets.ADMIN_API_KEY }}/g" \
            -e "s/{{BLOG_TITLE}}/${{ vars.BLOG_TITLE }}/g" \
            _config/config.template.php > _config/config.php
    
    - name: Deploy to Strato via SFTP
      uses: wangyucode/sftp-upload-action@v2.0.4
      with:
        host: ${{ vars.FTP_HOST }}
        port: ${{ vars.FTP_PORT }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        localDir: ./
        remoteDir: ${{ vars.FTP_REMOTE_DIR }}
        exclude: .git,.github,.gitignore,README,LICENSE,_config/config.template.php
    
    - name: Trigger Update Script
      run: |
        curl -v -f -X POST -H "Authorization: Bearer ${{ secrets.ADMIN_API_KEY }}" "${{ vars.BLOG_URL }}/admin/update"
