name: Deploy Blog

on:
  push:
    branches: [ pain ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install PHP dependencies   
        working-directory: src  
        run: composer install --no-dev --optimize-autoloader

      # (falls ihr weiterhin eine src/Config.template.php nutzt)
      - name: Create src/Config.php   
        working-directory: src  
        run: |
          sed \
            -e "s/{{DB_HOST}}/${{ vars.DB_HOST }}/g" \
            -e "s/{{DB_NAME}}/${{ vars.DB_NAME }}/g" \
            -e "s/{{DB_USER}}/${{ secrets.DB_USER }}/g" \
            -e "s/{{DB_PASS}}/${{ secrets.DB_PASS }}/g" \
            -e "s/{{ADMIN_API_KEY}}/${{ secrets.ADMIN_API_KEY }}/g" \
            -e "s/{{BLOG_TITLE}}/${{ vars.BLOG_TITLE }}/g" \
            Config.template.php > Config.php

         # ────────────────────────────────────────────────────────────────
      # 2) Prepare publish directory (copy src → publish, excluding templates etc.)
      - name: Prepare publish directory
        run: |
          mkdir -p publish
          rsync -a \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='README' \
            --exclude='LICENSE' \
            --exclude='Config.template.php' \
            --exclude='composer.*' \
            ./src/ ./publish/

      # ────────────────────────────────────────────────────────────────
      # 3) Deployment per SFTP – jetzt aus publish/wwwroot in dein Web-Root
      - name: Deploy to Strato via SFTP
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ vars.FTP_HOST }}
          port: ${{ vars.FTP_PORT }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          localDir: ./publish
          remoteDir: ${{ vars.FTP_REMOTE_DIR }}       

      # ─────────────────────────────────────────────────────────────────
      # 4) Trigger des Update-Skripts
      - name: Trigger Update Script
        run: |
          curl -fsS -X POST \
            -H "Authorization: Bearer ${{ secrets.ADMIN_API_KEY }}" \
            "${{ vars.BLOG_URL }}/admin/update"
